### ISSUE TITLE
Align Codebase Terminology with AnnoQ terminology and standards

### ISSUE THREAD

**Issue by tmushayahama** [USCbiostats/annoq-api-v2#10]
### Overview
To maintain consistency with AnnoQ terminology and improve the readability and clarity of our codebase, we propose renaming certain terms currently used in our application. This change will help new developers understand the codebase more quickly and align AnnoQ naming conventions 

### Proposed Changes

- Rename annoqData to snp and snps
- Change field/columns to annotation
- AnnoqTree will be annotations

### Action Items

- [x]  Update all occurrences to the new terms, ensuring that all references in the code, comments, documentation, and configuration files are modified.
- [x]  Perform thorough testing to ensure that the renaming does not affect the application's functionality.
- [x]  Review the changes, ensure consistency and accuracy in the use of the new terminology.

 
 @huaiyumi let us know what other standards and words to use
 
 But basically, my assumptions 

-  **snp** is the row
-  **snps** is table
-  **annotation** is field or column name
-  **annotations** current annoq-tree is annotations

tagging @akshala @huaiyumi

**Comment by akshala** [comment]
Commit 00d2e08 and f544369
