### ISSUE TITLE
Add Endpoint to Expose API Field Mappings for GraphQL

### ISSUE THREAD

**Issue by tmushayahama** [USCbiostats/annoq-api-v2#11]
### Overview

To enhance our API's usability and provide clarity to the end-users, we propose adding a new endpoint that will offer a clear mapping of our internal fields to the **api_field** names expected by our GraphQL implementation. This endpoint will assist users in understanding how our Elasticsearch data correlates with the GraphQL fields, thereby improving the API's intuitiveness and ease of use.

### Task Description

**GET Endpoint - GET /annotations:**
This endpoint should mirror the functionality provided by the existing annoq-tree endpoint but with an added focus on the **api_field** mappings https://github.com/USCbiostats/annoq-api/blob/c640da3ffeb3127cf54771b490d6a24005954222/api.py#L28

**example mapping** 

- 1000Gp3_AFR_AF to _1000Gp3_AFR_AF (no variable can start with a digit
- removing the (, ), [, ]

### For Future
Maybe put the json file into a database elasticsearch such that it will not be accessed as a flat file

tagging @akshala @huaiyumi 
For @quemeb this will come in handy on the config file update. But will update you later

**Comment by akshala** [comment]
Added in commit 6a74703

**Comment by akshala** [comment]
Commit cff862c
