### ISSUE TITLE
dealing with automatically generated files and logistics of scripts

### ISSUE THREAD

**Issue by tmushayahama** [USCbiostats/annoq-api-v2#12]
Continuation from https://github.com/USCbiostats/annoq-api-v2/issues/9

Just to clarify on the scripts. The folder will contain only scripts related files, not the generated results nor the input. So if the snp_model.py is generated, it should reside in the appropriate place, in this case src/graphql/models . Here are couple of options you can choose one best

### 1. Inside the Existing Models Directory

You can place snp_model.py directly in the models folder:
```
annoq_api/
│
├── src/
│   ├── graphql/
│   │   └── models/
│   │       ├── annotation_model.py
│   │       ├── stats_model.py
│   │       ├── autocomplete_model.py
│   │       └── snp_model.py       # Generated model or use snp_model_g.py
```

- Keeps all models consolidated in one location, making them easy to find. 
- Simplifies import paths, as all model imports would follow the same pattern.
- However, it might be harder to distinguish between manually written and generated code at a glance.

### 2. In a Dedicated generated Directory
Alternatively, you can create a specific generated folder either inside the models directory or at the same level but still under src. This method clearly separates your manually maintained models from the automatically generated ones.

```
annoq_api/
│
├── src/
│   ├── graphql/
│   │   └── models/
│   │       ├── generated/
│   │       │   └── snp_model.py   # Generated model
│   │       ├── annotation_model.py
│   │       ├── stats_model.py
│   │       └── autocomplete_model.py
```

- Clearly distinguishes generated code from manually written code.

### Action Items

- [x] Choose on of the above or anything
- [x] Either case, exclude the snp_model or entire generated folder from version control by adding it to gitignore
- [x] Something to think about: For docs, combine the script such that the generation is done as a forced pre-script like pipeline
      _bash generate_things.sh && python start server script or
      python scripts/class_generation.py && pythoon -m start annoq_api_

tagging @akshala @huaiyumi

**Comment by akshala** [comment]
So just the code used for generating would be in script but the generated json and generated code need to be in models? @tmushayahama

**Comment by tmushayahama** [comment]
@akshala only the models, not json since it is not being used right?

**Comment by akshala** [comment]
@tmushayahama the json is being used finally for generating the code using datamodel-codegen command

**Comment by akshala** [comment]
Also for now I had put the types for attributes as Optional[Annotation] and then replaced Any with Annotation since there was no way to assign the attribute type as Annotation. (This is something created by me in strawberry).

**Comment by akshala** [comment]
Commit 917d4b9 has a bash script which handles the whole generating part

**Comment by akshala** [comment]
Pull request #17 #14
