### ISSUE TITLE
Download API

### ISSUE THREAD

**Issue by akshala** [USCbiostats/annoq-api-v2#15]
Implementing the download api along with scrolling

**Comment by akshala** [comment]
Pull request #16

**Comment by tmushayahama** [comment]
Download will have 2 parts. 

- [x] Generating the file which is being done by download and return the file location
- [ ] Fast api endpoint called /download or /download_file which takes in the file_location returned above and return the file

For your reference this is a sample from Flask https://github.com/USCbiostats/annoq-api/blob/c640da3ffeb3127cf54771b490d6a24005954222/api.py#L48

tagging @akshala

**Comment by akshala** [comment]
Pull request #20
