### ISSUE TITLE
Search by Vfc- Usage example

### ISSUE THREAD

**Issue by tmushayahama** [USCbiostats/annoq-api-v2#24]
For this issue https://github.com/USCbiostats/annoq-api-v2/issues/23 also consider

To demo a usage example for vcf, since we don't have search by vcf, but search by ids, you will have to show in usage by reading a vcf file and converting it to AnnoQ elasticsearch ids. Here is the code on annoq site in JS https://github.com/USCbiostats/annoq-site/blob/397f4c25f9929b8f27722f2dfaa23d513efa727d/src/app/main/apps/snp/services/snp.service.ts#L257

An example vcf file format is here
https://github.com/USCbiostats/annoq-site/blob/master/src/%40annoq.common/data/sample-vcf.ts
    

### Steps
-  es ids are just **chrNum+:+ rsid+ref+>+alt** // double check this
-  extract that as shown on the above code   ` ${line[0].replace('chr', '')}:${line[1]}${line[3]}>${line[4]}`
-  then call the search_by_ids

so the clients should extract their vcfs and send the ids unless there is a need for the api

@akshala

**Comment by akshala** [comment]
Pull request #25
