### ISSUE TITLE
Reorganize Repo to enhance scalability and clarity

### ISSUE THREAD

**Issue by tmushayahama** [USCbiostats/annoq-api-v2#9]
### Overview
We aim to reorganize the project repository to enhance scalability and maintain a clear separation of concerns. This involves structuring the src, test, and scripts directories

### Proposed Structure
src/ (Source Code)
test/ (Tests)
scripts/ (Utility Scripts)

```
annoq-api/
│
├── src/
│     ├── main.py              # FastAPI app initialization, includes non-GraphQL endpoints
│     ├── graphql/
│     │   ├── schema.py        # Main GraphQL schema file, idk if these are gonna be multiple in the future
│     │   ├── resolvers/
│     │   │   ├── snp_resolver.py
│     │   │   ├── annotation_resolver.py
│     │   │   ├── stats_resolver.py
│     │   │   └── autocomplete_resolver.py
│     │   └── models/
│     │       ├── snp_model.py
│     │       ├── annotation_model.py
│     │       ├── stats_model.py
│     │       └── autocomplete_model.py
│     ├── external/ # Maybe we can come up with something else 
│     │   ├── downloader.py  
│     └── config/
├── test/
    ├── unit/
    │   ├── test_module1.py
    │   └── test_module2.py
    ├── functional/
    │   ├── test_feature1.py
    │   └── test_feature2.py
    ├── integration/
    │   ├── test_integration1.py
    │   └── test_integration2.py
└── scripts/
    └── class_generators/
        ├── generator.py 
        └── utils.py 
```

### Goals

- Scalability: Ensure the project structure supports expansion.
- Clarity: Maintain clear separation between different parts of the project (source code, tests, scripts).
- Ease of Use: Facilitate easier navigation and understanding of the project structure for new contributors.

### Action Items

- [x] Class Generators: Create a dedicated folder for class generators outside src folder
- [x] Add an .env-example 
- [x] Restructure the src directory to incorporate the Strawberry GraphQL setup as above
- [x] Organize the test directory to reflect the structure of the src directory.
- [x] Set up a class generators folder in the scripts directory to support script-based class generation.
- [x] Add the generated code into gitignore file so they will not be tracked

tagging @akshala @huaiyumi

**Comment by akshala** [comment]
Commit a599413 and 37b8ee5

**Comment by tmushayahama** [comment]
@akshala the ANNOTATION_API should not be "http://annoq.org/api" because your api will replace this api, so the url will not exist.. Rather just do a json file open like how it is implemented on the v1

**Comment by akshala** [comment]
@tmushayahama made the changes in commit a151e2a
